import = ["./rose-pine-dawn.toml"]

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 14.0

[font.bold]
family = "Menlo"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "Menlo"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.8
blur = true
dynamic_padding = true
padding = { x = 8, y = 8 }
dimensions = { columns = 150, lines = 38 }
position = { x = 1000, y = 500 }
decorations_theme_variant = "Dark"
