#!/usr/bin/env bash

echo 'Are the Xcode command line tools installed?'
echo 'If not exit using CMD+C, and install with:'
echo 'xcode-select -install'


read answer


#echo ' ' 
#echo 'What is your username on this system?'
#read uname

sudo -v #Give sudo privileges ahead of time, so that we hopefully only have to enter a password once
cd ~ #Moving to home directory at the beginning of the process

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" #Installing homebrew

#<----------------Installing MacOS Apps, via Homebrew, Caks, & The App Store-------------------->
brew=(
  curl
  fzf
  neofetch
  neovim
  node
  python
  python@3.9
  tmux
  tree
  watchman
  yarn
  fish
  exa
)

cask=(
  alacritty
  firefox
  notion
  rectangle
  spotify
)

mas=(
 497799835 #Xcode 
)

git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
brew update
#brew upgrade

brew install ${brew[@]}
brew install --cask ${cask[@]}
mas install ${mas[@]}

cd ~
#mkdir repo
#cd repo
#git clone https://github.com/romerorickyio/dotfiles.git


#ln -s ~/repo-path-file ~/local-config-location
ln -s ~/repo/dotfiles/.config ~/.config
# ln -s ~/repo/dotfiles/config/zsh/.zshrc ~/.zshrc
ln -s ~/repo/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/repo/dotfiles/.config/nvim/init.vim ~/.vimrc

#Installing Vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

echo 'Run ":PlugInstall" to install Vim Plugins, and then exit' >> ~/vimPlug
vim ~/vimPlug #Opening Vim
rm ~/vimPlug #Removing vimPlug

#./mac-preferences-setup

# fish setup
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install oh-my-fish/theme-robbyrussell
fisher install jethrokuan/z
fisher install oh-my-fish/plugin-peco


echo 'Installation Complete'

