#!/usr/bin/env bash
# https://asdf-vm.com
# https://github.com/asdf-community

#  install asdf
# install go
# go install github.com/asdf-vm/asdf/cmd/asdf@v0.18.0

# nodejs
# asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
# asdf install nodejs latest
# asdf set -u nodejs latest

# ruby https://github.com/asdf-vm/asdf-ruby
# asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
# brew install readline libyaml gmp
# linux: sudo apt install -y autoconf patch build-essential rustc libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libgmp-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev uuid-dev
# asdf install ruby latest
# asdf set -u ruby latest

# golang
# asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
# asdf install golang latest
# asdf set -u golang latest

# python https://github.com/asdf-community/asdf-python
# asdf plugin add python https://github.com/asdf-community/asdf-python.git
# asdf install python latest
# asdf set -u python latest

# cat $HOME/.tool-versions
