#!/usr/bin/env bash
# https://asdf-vm.com
# https://github.com/asdf-community

#  install asdf
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0

# nodejs
# asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
# asdf install nodejs latest
# asdf global nodejs latest

# ruby https://github.com/asdf-vm/asdf-ruby
# asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
# brew install readline libyaml gmp
# asdf install ruby latest
# asdf global ruby latest

# golang
# asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
# asdf install golang latest
# asdf global golang latest

# python https://github.com/asdf-community/asdf-python
# asdf plugin-add python
# asdf install python latest
# asdf global python latest

# cat $HOME/.tool-versions